// This file is auto-generated by scripts/generate-icons.mjs
// Do not edit manually.

import LucrTradeSvg from './LucrTrade.svg';
import BinanceSvg from './platforms/Binance.svg';
import BitgetSvg from './platforms/Bitget.svg';
import BybitSvg from './platforms/Bybit.svg';
import InteractiveBrokersSvg from './platforms/Interactive Brokers.svg';
import MetaTraderSvg from './platforms/MetaTrader.svg';
import OKXSvg from './platforms/OKX.svg';

export const GeneratedCoreIconsSvg = {
	"LucrTrade": LucrTradeSvg,
} as const;

export const GeneratedPlatformIconsSvg = {
	"Binance": BinanceSvg,
	"Bitget": BitgetSvg,
	"Bybit": BybitSvg,
	"Interactive Brokers": InteractiveBrokersSvg,
	"MetaTrader": MetaTraderSvg,
	"OKX": OKXSvg,
} as const;
