import esbuild from "esbuild";
import process from "process";
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const environment = process.argv[2] ?? 'development';
const shouldWatch = process.argv[3] === 'watch';
const prod = environment === 'production';
const defaultLucrchartUrl = 'https://lucrchart.lucrtrade.com/';
const lucrchartUrl = prod ? defaultLucrchartUrl : process.env.LUCRCHART_URL ?? defaultLucrchartUrl;
const buildTimestamp = Date.now().toString();
const packageJson = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8'));
const chartVersion = packageJson.chart_version;
if (typeof chartVersion !== 'string' || !/^\d+\.\d+$/.test(chartVersion)) {
	throw new Error('package.json chart_version must be a major.minor string');
}
const lucrchartIframeUrl = `${lucrchartUrl.replace(/\/$/, '')}/lv/${chartVersion}`;
const packageRepository = typeof packageJson.repository === 'string'
	? packageJson.repository
	: packageJson.repository.url;
const gitCommitSha = (process.env.GITHUB_SHA ?? execFileSync('git', ['rev-parse', '--short=12', 'HEAD'], {
	encoding: 'utf8',
})).trim();

const plugins = lucrchartUrl === defaultLucrchartUrl ? [] : [{
	name: 'lucrchart-url',
	setup(build) {
		build.onLoad({ filter: /\/src\/constant\.ts$/ }, (args) => {
			const source = readFileSync(args.path, 'utf8');
			const nextSource = source.replace(
				`export const LUCRCHART_URL = '${defaultLucrchartUrl}'`,
				`export const LUCRCHART_URL = ${JSON.stringify(lucrchartUrl)}`,
			);
			if (nextSource === source) {
				throw new Error('LUCRCHART_URL constant not found');
			}
			return {
				contents: nextSource,
				loader: 'ts',
			};
		});
	},
}];

const context = await esbuild.context({
	alias: {
		"onnxruntime-web": "onnxruntime-web/all",
		"ppu-ocv/canvas": "ppu-ocv/canvas-web",
	},
	banner: {
		js: banner,
	},
	define: {
		__LUCRJOURNAL_BUILD_ENVIRONMENT__: JSON.stringify(environment),
		__LUCRJOURNAL_GIT_COMMIT_SHA__: JSON.stringify(gitCommitSha),
		__LUCRJOURNAL_BUILD_TIMESTAMP__: JSON.stringify(buildTimestamp),
		__LUCRJOURNAL_REPOSITORY__: JSON.stringify(packageRepository),
		__LUCRJOURNAL_CHART_VERSION__: JSON.stringify(chartVersion),
		__LUCRJOURNAL_CHART_IFRAME_URL__: JSON.stringify(lucrchartIframeUrl),
		'import.meta.vitest': 'undefined',
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	platform: "node",
	target: "es2020",
	logLevel: "info",
	loader: {
		'.md': 'text',
		'.svg': 'text',
	},
	plugins,
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod || !shouldWatch) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
