import esbuild from "esbuild";
import process from "process";
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync } from 'node:fs';
import { builtinModules } from 'node:module';
import { fileURLToPath } from 'node:url';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const environment = process.argv[2] ?? 'development';
const shouldWatch = process.argv[3] === 'watch';
const prod = environment === 'production';
const defaultLucrchartUrl = 'https://lucrchart.lucrtrade.com/';
const lucrchartUrl = prod ? defaultLucrchartUrl : process.env.LUCRCHART_URL ?? defaultLucrchartUrl;
const buildTimestamp = Date.now().toString();
const packageJson = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8'));
const chartVersion = packageJson.chart_version;
if (typeof chartVersion !== 'string' || !/^\d+\.\d+$/.test(chartVersion)) {
	throw new Error('package.json chart_version must be a major.minor string');
}
const lucrchartIframeUrl = `${lucrchartUrl.replace(/\/$/, '')}/lv/${chartVersion}`;
const packageRepository = typeof packageJson.repository === 'string'
	? packageJson.repository
	: packageJson.repository.url;
const gitCommitSha = (process.env.GITHUB_SHA ?? execFileSync('git', ['rev-parse', '--short=12', 'HEAD'], {
	encoding: 'utf8',
})).trim();

const reactDomClientScriptResourcePlugin = {
	name: 'react-dom-client-script-resource',
	setup(build) {
		build.onLoad({ filter: /react-dom\/cjs\/react-dom-client\.(production|development)\.js$/ }, (args) => {
			return {
				contents: stripReactDomClientScriptResources(readFileSync(args.path, 'utf8'), args.path),
				loader: 'js',
			};
		});
	},
};

function replaceRequiredPattern(source, pattern, replacement, expected, label) {
	const count = [...source.matchAll(pattern)].length;
	if (count !== expected) {
		throw new Error(`${label}: expected ${expected} React DOM script resource replacement(s), found ${count}`);
	}
	return source.replace(pattern, replacement);
}

function stripReactDomClientScriptResources(source, label) {
	let nextSource = source;
	nextSource = replaceRequiredPattern(nextSource, /\s*\(resource = ownerDocument\.createElement\("script"\)\),\n\s*markNodeAsHoistable\(resource\),\n\s*setInitialProperties\(resource, "link", src\),\n\s*ownerDocument\.head\.appendChild\(resource\)/g, `
        (resource = null)`, 2, label);
	nextSource = replaceRequiredPattern(nextSource, /\s*styleProps = hoistableRoot\.createElement\("script"\);\n\s*markNodeAsHoistable\(styleProps\);\n\s*setInitialProperties\(styleProps, "link", instance\);\n\s*hoistableRoot\.head\.appendChild\(styleProps\);\n\s*return \(resource\.instance = styleProps\);/g, `
        return (resource.instance = null);`, 1, label);
	return nextSource;
}

// ccxt ships 130+ exchanges and is not tree-shakeable; bundle only the exchanges
// that a platform actually declares via `ccxtId`, derived straight from src/platforms
// so the build stays in sync with the single source of truth. Per-exchange files are
// reached by absolute path to bypass ccxt's `exports` field, which blocks subpaths.
const ccxtSrcDir = new URL('./node_modules/ccxt/js/src/', import.meta.url);
const platformsDir = new URL('./src/platforms/', import.meta.url);

function resolveCcxtExchangeIds() {
	const ids = new Set();
	for (const file of readdirSync(platformsDir)) {
		if (!file.endsWith('.ts')) continue;
		const match = readFileSync(new URL(file, platformsDir), 'utf8').match(/ccxtId:\s*'([^']+)'/);
		if (match) ids.add(match[1]);
	}
	return [...ids];
}

const ccxtSlimPlugin = {
	name: 'ccxt-slim',
	setup(build) {
		const ids = resolveCcxtExchangeIds();
		if (ids.length === 0) {
			throw new Error('ccxt-slim: no ccxtId found in src/platforms');
		}
		build.onResolve({ filter: /^ccxt$/ }, () => ({ path: 'ccxt-slim', namespace: 'ccxt-slim' }));
		build.onLoad({ filter: /.*/, namespace: 'ccxt-slim' }, () => ({
			contents: ids
				.map((id) => `export { default as ${id} } from ${JSON.stringify(fileURLToPath(new URL(`${id}.js`, ccxtSrcDir)))};`)
				.join('\n'),
			resolveDir: fileURLToPath(ccxtSrcDir),
			loader: 'js',
		}));
	},
};

const plugins = [reactDomClientScriptResourcePlugin, ccxtSlimPlugin, ...(lucrchartUrl === defaultLucrchartUrl ? [] : [{
	name: 'lucrchart-url',
	setup(build) {
		build.onLoad({ filter: /\/src\/constant\.ts$/ }, (args) => {
			const source = readFileSync(args.path, 'utf8');
			const nextSource = source.replace(
				`export const LUCRCHART_URL = '${defaultLucrchartUrl}'`,
				`export const LUCRCHART_URL = ${JSON.stringify(lucrchartUrl)}`,
			);
			if (nextSource === source) {
				throw new Error('LUCRCHART_URL constant not found');
			}
			return {
				contents: nextSource,
				loader: 'ts',
			};
		});
	},
}])];

const context = await esbuild.context({
	alias: {
		"onnxruntime-web": "onnxruntime-web/all",
		"ppu-ocv/canvas": "ppu-ocv/canvas-web",
	},
	banner: {
		js: banner,
	},
	define: {
		'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
		__LUCRJOURNAL_BUILD_ENVIRONMENT__: JSON.stringify(environment),
		__LUCRJOURNAL_GIT_COMMIT_SHA__: JSON.stringify(gitCommitSha),
		__LUCRJOURNAL_BUILD_TIMESTAMP__: JSON.stringify(buildTimestamp),
		__LUCRJOURNAL_REPOSITORY__: JSON.stringify(packageRepository),
		__LUCRJOURNAL_CHART_VERSION__: JSON.stringify(chartVersion),
		__LUCRJOURNAL_CHART_IFRAME_URL__: JSON.stringify(lucrchartIframeUrl),
		'import.meta.vitest': 'undefined',
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	platform: "node",
	target: "es2020",
	logLevel: "info",
	loader: {
		'.md': 'text',
		'.svg': 'text',
	},
	plugins,
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod || !shouldWatch) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
