// Generated by scripts/sync-account-contract.ts from packages/account/src/contract.ts. Do not edit.

export const FEATURE_KEYS = [
	'journal_basic',
	'journal_advanced',
	'indicator_bundle',
] as const

export type FeatureKey = (typeof FEATURE_KEYS)[number]

export const PLAN_KEYS = ['lucrtrade', 'lucrjournal'] as const
export type AccountPlanKey = (typeof PLAN_KEYS)[number]

export const PRODUCT_KEYS = ['indicator_bundle'] as const
export type AccountProductKey = (typeof PRODUCT_KEYS)[number]

export const SUBSCRIPTION_STATUSES = [
	'incomplete',
	'incomplete_expired',
	'trialing',
	'active',
	'past_due',
	'canceled',
	'unpaid',
	'paused',
] as const

export type AccountSubscriptionStatus = (typeof SUBSCRIPTION_STATUSES)[number]

export type AccountProfile = {
	userId: string
	username: string | null
	displayName: string | null
	avatarUrl: string | null
	email: string | null
}

export type AccountEntitlements = {
	features: FeatureKey[]
}

export type AccountPlan = {
	key: AccountPlanKey
	status: AccountSubscriptionStatus
} | null

export type AccountContext = {
	profile: AccountProfile
	entitlements: AccountEntitlements
	plan: AccountPlan
	products: AccountProductKey[]
}

export function isFeatureKey(value: string): value is FeatureKey {
	return (FEATURE_KEYS as readonly string[]).includes(value)
}

export function isPlanKey(value: string): value is AccountPlanKey {
	return (PLAN_KEYS as readonly string[]).includes(value)
}

export function isProductKey(value: string): value is AccountProductKey {
	return (PRODUCT_KEYS as readonly string[]).includes(value)
}

export function isSubscriptionStatus(
	value: string,
): value is AccountSubscriptionStatus {
	return (SUBSCRIPTION_STATUSES as readonly string[]).includes(value)
}

export function hasFeature(
	entitlements: AccountEntitlements,
	feature: FeatureKey,
): boolean {
	return entitlements.features.includes(feature)
}
